# Generated by Django 5.2.3 on 2025-07-04 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventApp', '0002_alter_event_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='endTime',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
