# Generated by Django 5.2.3 on 2025-07-04 08:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventApp', '0003_event_endtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='endTime',
            field=models.TimeField(default=datetime.time(17, 0)),
        ),
    ]
